name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d app_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      APP_ENV: test
      APP_SECRET: test_secret
      DEFAULT_URI: http://localhost
      DATABASE_URL: postgresql://app:app@127.0.0.1:5432/app_test?serverVersion=16&charset=utf8

      JWT_PASSPHRASE: test_passphrase
      JWT_SECRET_KEY: config/jwt/private.pem
      JWT_PUBLIC_KEY: config/jwt/public.pem

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer
          extensions: intl, pdo_pgsql, zip

      - name: Create .env (CI)
        run: |
          cat > .env <<'EOF'
          APP_ENV=test
          APP_SECRET=test_secret
          DEFAULT_URI=http://localhost
          DATABASE_URL=postgresql://app:app@127.0.0.1:5432/app_test?serverVersion=16&charset=utf8
          EOF

      - name: Install dependencies (no scripts)
        run: composer install --no-interaction --prefer-dist --no-scripts

      - name: Generate JWT keys (CI)
        run: |
          mkdir -p config/jwt
          php bin/console lexik:jwt:generate-keypair --overwrite

      - name: Clear cache (test)
        run: php bin/console cache:clear --env=test

      - name: Create database & run migrations
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --env=test

      - name: Run tests
        run: php bin/phpunit
